spring:
  datasource:
    url: jdbc:postgresql://silly.db.elephantsql.com:5432/hakpimrh
    username: hakpimrh
    password: NZyYHUnWPnJPabT7wwAYI5cQ-Bn_Y6Ey
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  